name: Generate Datas

permissions:
  contents: write   # <-- allow pushing to the repo
  pages: write      # <-- if using GitHub Pages
  id-token: write   # <-- required for pages deployments sometimes

on:
  schedule:
    - cron: "0 * * * *" # every 1 hour
  workflow_dispatch:

jobs:
  build:
    name: Jobs to update datas
    runs-on: ubuntu-latest
    steps:
      # Snake Animation
      - uses: Platane/snk@master
        id: snake-gif
        with:
          github_user_name: jishanahmed-shaikh
          svg_out_path: dist/github-contribution-grid-snake.svg

      - uses: crazy-max/ghaction-github-pages@v2.1.3
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
